@startuml

title 打开百度www.baidu.com
Actor User
' autonumber 启用了显示前导序号; 另外本行'开头是注释
autonumber
User -> 浏览器: 输入http://www.baidu.com

group DNS查询
浏览器 -> DNS服务器: www.baidu.com这台主机的IP是多少？
DNS服务器 --> 浏览器: www.baidu.com的IP是119.75.217.109
end

participant 百度Web服务器1 as BWS1
浏览器 -[#0000FF]> BWS1: 真正发请求给百度Web服务器
BWS1 --> 浏览器: 百度首页

participant 百度Web服务器2 #FFF

浏览器 -> 浏览器: 解析百度首页html,其中有图片 js css等\n比如其中有ss0.bdstatic.com/1.jpg等资源

alt 已简化，其实与上面请求www.baidu.com一样要DNS查询
浏览器 -> 百度图片服务器1: 请求百度logo
百度图片服务器1 --> 浏览器: 返回百度logo

浏览器 -> 百度图片服务器2: 请求新闻图片
百度图片服务器2 --> 浏览器: 返回新闻图片
end

浏览器 --> User: 加载完毕


note right of BWS1: 我IP是119.75.217.109,今天的主唱
note right of 百度Web服务器2 #FFAAAA: 我IP是119.75.217.110 我今天来围观的

'note right
'    这里是一个真实的请求
'    <img src="./img/I_OPEN_WWW.BAIDU.COM.png">
'end note

legend center
    下面是个活的,和上面的有差别。
    图片中的 1、2是因为百度要求用https访问做了302跳转
    图片中的 12是DNS查询时间，而所在的小框中是356ms的细节展开

    <img src="./img/I_OPEN_WWW.BAIDU.COM.png">
endlegend

@enduml