@startuml
title Extjs4 数据流
skinparam package<<Layout>> {
  borderColor Transparent
  backgroundColor Transparent
  fontColor Transparent
  stereotypeFontColor Transparent
}
skinparam shadowing false

package foo <<Layout>> {
    storage "Data Source" as DS
    storage "Proxy" as P
}
storage "Reader" as R
storage "Writer" as W
storage "Records" as Rs


storage Consumer {
    component grid
    component tree
    component view
    component combo
    component chart
}

database "Data Store" as Store


DS -r-> P
P .l.> DS
P -u-> R
W .u.>> P
R -> Rs

Rs -d-> Store
Store .l.>> W
Store ---> Consumer
Consumer ..> Store
@enduml